//{"in":0,"out":1}
int hook(int argId, int id) {
	int gID = get_global_id(0);
	printf("%d,%d,%d\n", gID, argId, id);
	return id;
}
kernel void median(global unsigned* in, global unsigned* out) {
  unsigned x = get_global_id(1);
  unsigned y = get_global_id(0);
  unsigned rowLen = get_global_size(0);
  unsigned p00, p01, p02;
  unsigned p10, p11, p12;
  unsigned p20, p21, p22;
  unsigned res = 0;

  bool border = x < 1 | y < 1 | (x > rowLen - 2) | (y > rowLen - 2);
  if (border)
    return;

  p00 = in[hook(0, (x - 1) * rowLen + y - 1)];
  p10 = in[hook(0, x * rowLen + y - 1)];
  p20 = in[hook(0, (x + 1) * rowLen + y - 1)];
  p01 = in[hook(0, (x - 1) * rowLen + y)];
  p11 = in[hook(0, x * rowLen + y)];
  p21 = in[hook(0, (x + 1) * rowLen + y)];
  p02 = in[hook(0, (x - 1) * rowLen + y + 1)];
  p12 = in[hook(0, x * rowLen + y + 1)];
  p22 = in[hook(0, (x + 1) * rowLen + y + 1)];

  unsigned p00r, p01r, p02r;
  unsigned p10r, p11r, p12r;
  unsigned p20r, p21r, p22r;

  p00r = p00 & 255;
  p01r = p01 & 255;
  p02r = p02 & 255;
  p10r = p10 & 255;
  p11r = p11 & 255;
  p12r = p12 & 255;
  p20r = p20 & 255;
  p21r = p21 & 255;
  p22r = p22 & 255;

  {
    unsigned pos_a, pos_b, pos_c;
    unsigned tmp_a, tmp_b;
    unsigned a_bigger_b, a_bigger_c;
    unsigned b_bigger_c;
    a_bigger_b = (p00r) > (p01r);
    a_bigger_c = (p00r) > (p02r);
    b_bigger_c = (p01r) > (p02r);
    pos_a = a_bigger_c + a_bigger_b;
    pos_b = !a_bigger_b + b_bigger_c;
    pos_c = !a_bigger_c + !b_bigger_c;
    tmp_a = (p00r);
    tmp_b = (p01r);
    (p00r) = pos_b == 0 ? (p01r) : (p00r);
    (p00r) = pos_c == 0 ? (p02r) : (p00r);
    (p01r) = pos_a == 1 ? tmp_a : (p01r);
    (p01r) = pos_c == 1 ? (p02r) : (p01r);
    (p02r) = pos_a == 2 ? tmp_a : (p02r);
    (p02r) = pos_b == 2 ? tmp_b : (p02r);
  };
  {
    unsigned pos_a, pos_b, pos_c;
    unsigned tmp_a, tmp_b;
    unsigned a_bigger_b, a_bigger_c;
    unsigned b_bigger_c;
    a_bigger_b = (p10r) > (p11r);
    a_bigger_c = (p10r) > (p12r);
    b_bigger_c = (p11r) > (p12r);
    pos_a = a_bigger_c + a_bigger_b;
    pos_b = !a_bigger_b + b_bigger_c;
    pos_c = !a_bigger_c + !b_bigger_c;
    tmp_a = (p10r);
    tmp_b = (p11r);
    (p10r) = pos_b == 0 ? (p11r) : (p10r);
    (p10r) = pos_c == 0 ? (p12r) : (p10r);
    (p11r) = pos_a == 1 ? tmp_a : (p11r);
    (p11r) = pos_c == 1 ? (p12r) : (p11r);
    (p12r) = pos_a == 2 ? tmp_a : (p12r);
    (p12r) = pos_b == 2 ? tmp_b : (p12r);
  };
  {
    unsigned pos_a, pos_b, pos_c;
    unsigned tmp_a, tmp_b;
    unsigned a_bigger_b, a_bigger_c;
    unsigned b_bigger_c;
    a_bigger_b = (p20r) > (p21r);
    a_bigger_c = (p20r) > (p22r);
    b_bigger_c = (p21r) > (p22r);
    pos_a = a_bigger_c + a_bigger_b;
    pos_b = !a_bigger_b + b_bigger_c;
    pos_c = !a_bigger_c + !b_bigger_c;
    tmp_a = (p20r);
    tmp_b = (p21r);
    (p20r) = pos_b == 0 ? (p21r) : (p20r);
    (p20r) = pos_c == 0 ? (p22r) : (p20r);
    (p21r) = pos_a == 1 ? tmp_a : (p21r);
    (p21r) = pos_c == 1 ? (p22r) : (p21r);
    (p22r) = pos_a == 2 ? tmp_a : (p22r);
    (p22r) = pos_b == 2 ? tmp_b : (p22r);
  };

  {
    unsigned pos_a, pos_b, pos_c;
    unsigned tmp_a, tmp_b;
    unsigned a_bigger_b, a_bigger_c;
    unsigned b_bigger_c;
    a_bigger_b = (p00r) > (p10r);
    a_bigger_c = (p00r) > (p20r);
    b_bigger_c = (p10r) > (p20r);
    pos_a = a_bigger_c + a_bigger_b;
    pos_b = !a_bigger_b + b_bigger_c;
    pos_c = !a_bigger_c + !b_bigger_c;
    tmp_a = (p00r);
    tmp_b = (p10r);
    (p00r) = pos_b == 0 ? (p10r) : (p00r);
    (p00r) = pos_c == 0 ? (p20r) : (p00r);
    (p10r) = pos_a == 1 ? tmp_a : (p10r);
    (p10r) = pos_c == 1 ? (p20r) : (p10r);
    (p20r) = pos_a == 2 ? tmp_a : (p20r);
    (p20r) = pos_b == 2 ? tmp_b : (p20r);
  };
  {
    unsigned pos_a, pos_b, pos_c;
    unsigned tmp_a, tmp_b;
    unsigned a_bigger_b, a_bigger_c;
    unsigned b_bigger_c;
    a_bigger_b = (p01r) > (p11r);
    a_bigger_c = (p01r) > (p21r);
    b_bigger_c = (p11r) > (p21r);
    pos_a = a_bigger_c + a_bigger_b;
    pos_b = !a_bigger_b + b_bigger_c;
    pos_c = !a_bigger_c + !b_bigger_c;
    tmp_a = (p01r);
    tmp_b = (p11r);
    (p01r) = pos_b == 0 ? (p11r) : (p01r);
    (p01r) = pos_c == 0 ? (p21r) : (p01r);
    (p11r) = pos_a == 1 ? tmp_a : (p11r);
    (p11r) = pos_c == 1 ? (p21r) : (p11r);
    (p21r) = pos_a == 2 ? tmp_a : (p21r);
    (p21r) = pos_b == 2 ? tmp_b : (p21r);
  };
  {
    unsigned pos_a, pos_b, pos_c;
    unsigned tmp_a, tmp_b;
    unsigned a_bigger_b, a_bigger_c;
    unsigned b_bigger_c;
    a_bigger_b = (p02r) > (p12r);
    a_bigger_c = (p02r) > (p22r);
    b_bigger_c = (p12r) > (p22r);
    pos_a = a_bigger_c + a_bigger_b;
    pos_b = !a_bigger_b + b_bigger_c;
    pos_c = !a_bigger_c + !b_bigger_c;
    tmp_a = (p02r);
    tmp_b = (p12r);
    (p02r) = pos_b == 0 ? (p12r) : (p02r);
    (p02r) = pos_c == 0 ? (p22r) : (p02r);
    (p12r) = pos_a == 1 ? tmp_a : (p12r);
    (p12r) = pos_c == 1 ? (p22r) : (p12r);
    (p22r) = pos_a == 2 ? tmp_a : (p22r);
    (p22r) = pos_b == 2 ? tmp_b : (p22r);
  };

  {
    unsigned pos_a, pos_b, pos_c;
    unsigned tmp_a, tmp_b;
    unsigned a_bigger_b, a_bigger_c;
    unsigned b_bigger_c;
    a_bigger_b = (p00r) > (p11r);
    a_bigger_c = (p00r) > (p22r);
    b_bigger_c = (p11r) > (p22r);
    pos_a = a_bigger_c + a_bigger_b;
    pos_b = !a_bigger_b + b_bigger_c;
    pos_c = !a_bigger_c + !b_bigger_c;
    tmp_a = (p00r);
    tmp_b = (p11r);
    (p00r) = pos_b == 0 ? (p11r) : (p00r);
    (p00r) = pos_c == 0 ? (p22r) : (p00r);
    (p11r) = pos_a == 1 ? tmp_a : (p11r);
    (p11r) = pos_c == 1 ? (p22r) : (p11r);
    (p22r) = pos_a == 2 ? tmp_a : (p22r);
    (p22r) = pos_b == 2 ? tmp_b : (p22r);
  };

  res = p11r;

  unsigned p00g, p01g, p02g;
  unsigned p10g, p11g, p12g;
  unsigned p20g, p21g, p22g;

  p00g = (p00 >> 8) & 255;
  p01g = (p01 >> 8) & 255;
  p02g = (p02 >> 8) & 255;
  p10g = (p10 >> 8) & 255;
  p11g = (p11 >> 8) & 255;
  p12g = (p12 >> 8) & 255;
  p20g = (p20 >> 8) & 255;
  p21g = (p21 >> 8) & 255;
  p22g = (p22 >> 8) & 255;

  {
    unsigned pos_a, pos_b, pos_c;
    unsigned tmp_a, tmp_b;
    unsigned a_bigger_b, a_bigger_c;
    unsigned b_bigger_c;
    a_bigger_b = (p00g) > (p01g);
    a_bigger_c = (p00g) > (p02g);
    b_bigger_c = (p01g) > (p02g);
    pos_a = a_bigger_c + a_bigger_b;
    pos_b = !a_bigger_b + b_bigger_c;
    pos_c = !a_bigger_c + !b_bigger_c;
    tmp_a = (p00g);
    tmp_b = (p01g);
    (p00g) = pos_b == 0 ? (p01g) : (p00g);
    (p00g) = pos_c == 0 ? (p02g) : (p00g);
    (p01g) = pos_a == 1 ? tmp_a : (p01g);
    (p01g) = pos_c == 1 ? (p02g) : (p01g);
    (p02g) = pos_a == 2 ? tmp_a : (p02g);
    (p02g) = pos_b == 2 ? tmp_b : (p02g);
  };
  {
    unsigned pos_a, pos_b, pos_c;
    unsigned tmp_a, tmp_b;
    unsigned a_bigger_b, a_bigger_c;
    unsigned b_bigger_c;
    a_bigger_b = (p10g) > (p11g);
    a_bigger_c = (p10g) > (p12g);
    b_bigger_c = (p11g) > (p12g);
    pos_a = a_bigger_c + a_bigger_b;
    pos_b = !a_bigger_b + b_bigger_c;
    pos_c = !a_bigger_c + !b_bigger_c;
    tmp_a = (p10g);
    tmp_b = (p11g);
    (p10g) = pos_b == 0 ? (p11g) : (p10g);
    (p10g) = pos_c == 0 ? (p12g) : (p10g);
    (p11g) = pos_a == 1 ? tmp_a : (p11g);
    (p11g) = pos_c == 1 ? (p12g) : (p11g);
    (p12g) = pos_a == 2 ? tmp_a : (p12g);
    (p12g) = pos_b == 2 ? tmp_b : (p12g);
  };
  {
    unsigned pos_a, pos_b, pos_c;
    unsigned tmp_a, tmp_b;
    unsigned a_bigger_b, a_bigger_c;
    unsigned b_bigger_c;
    a_bigger_b = (p20g) > (p21g);
    a_bigger_c = (p20g) > (p22g);
    b_bigger_c = (p21g) > (p22g);
    pos_a = a_bigger_c + a_bigger_b;
    pos_b = !a_bigger_b + b_bigger_c;
    pos_c = !a_bigger_c + !b_bigger_c;
    tmp_a = (p20g);
    tmp_b = (p21g);
    (p20g) = pos_b == 0 ? (p21g) : (p20g);
    (p20g) = pos_c == 0 ? (p22g) : (p20g);
    (p21g) = pos_a == 1 ? tmp_a : (p21g);
    (p21g) = pos_c == 1 ? (p22g) : (p21g);
    (p22g) = pos_a == 2 ? tmp_a : (p22g);
    (p22g) = pos_b == 2 ? tmp_b : (p22g);
  };

  {
    unsigned pos_a, pos_b, pos_c;
    unsigned tmp_a, tmp_b;
    unsigned a_bigger_b, a_bigger_c;
    unsigned b_bigger_c;
    a_bigger_b = (p00g) > (p10g);
    a_bigger_c = (p00g) > (p20g);
    b_bigger_c = (p10g) > (p20g);
    pos_a = a_bigger_c + a_bigger_b;
    pos_b = !a_bigger_b + b_bigger_c;
    pos_c = !a_bigger_c + !b_bigger_c;
    tmp_a = (p00g);
    tmp_b = (p10g);
    (p00g) = pos_b == 0 ? (p10g) : (p00g);
    (p00g) = pos_c == 0 ? (p20g) : (p00g);
    (p10g) = pos_a == 1 ? tmp_a : (p10g);
    (p10g) = pos_c == 1 ? (p20g) : (p10g);
    (p20g) = pos_a == 2 ? tmp_a : (p20g);
    (p20g) = pos_b == 2 ? tmp_b : (p20g);
  };
  {
    unsigned pos_a, pos_b, pos_c;
    unsigned tmp_a, tmp_b;
    unsigned a_bigger_b, a_bigger_c;
    unsigned b_bigger_c;
    a_bigger_b = (p01g) > (p11g);
    a_bigger_c = (p01g) > (p21g);
    b_bigger_c = (p11g) > (p21g);
    pos_a = a_bigger_c + a_bigger_b;
    pos_b = !a_bigger_b + b_bigger_c;
    pos_c = !a_bigger_c + !b_bigger_c;
    tmp_a = (p01g);
    tmp_b = (p11g);
    (p01g) = pos_b == 0 ? (p11g) : (p01g);
    (p01g) = pos_c == 0 ? (p21g) : (p01g);
    (p11g) = pos_a == 1 ? tmp_a : (p11g);
    (p11g) = pos_c == 1 ? (p21g) : (p11g);
    (p21g) = pos_a == 2 ? tmp_a : (p21g);
    (p21g) = pos_b == 2 ? tmp_b : (p21g);
  };
  {
    unsigned pos_a, pos_b, pos_c;
    unsigned tmp_a, tmp_b;
    unsigned a_bigger_b, a_bigger_c;
    unsigned b_bigger_c;
    a_bigger_b = (p02g) > (p12g);
    a_bigger_c = (p02g) > (p22g);
    b_bigger_c = (p12g) > (p22g);
    pos_a = a_bigger_c + a_bigger_b;
    pos_b = !a_bigger_b + b_bigger_c;
    pos_c = !a_bigger_c + !b_bigger_c;
    tmp_a = (p02g);
    tmp_b = (p12g);
    (p02g) = pos_b == 0 ? (p12g) : (p02g);
    (p02g) = pos_c == 0 ? (p22g) : (p02g);
    (p12g) = pos_a == 1 ? tmp_a : (p12g);
    (p12g) = pos_c == 1 ? (p22g) : (p12g);
    (p22g) = pos_a == 2 ? tmp_a : (p22g);
    (p22g) = pos_b == 2 ? tmp_b : (p22g);
  };

  {
    unsigned pos_a, pos_b, pos_c;
    unsigned tmp_a, tmp_b;
    unsigned a_bigger_b, a_bigger_c;
    unsigned b_bigger_c;
    a_bigger_b = (p00g) > (p11g);
    a_bigger_c = (p00g) > (p22g);
    b_bigger_c = (p11g) > (p22g);
    pos_a = a_bigger_c + a_bigger_b;
    pos_b = !a_bigger_b + b_bigger_c;
    pos_c = !a_bigger_c + !b_bigger_c;
    tmp_a = (p00g);
    tmp_b = (p11g);
    (p00g) = pos_b == 0 ? (p11g) : (p00g);
    (p00g) = pos_c == 0 ? (p22g) : (p00g);
    (p11g) = pos_a == 1 ? tmp_a : (p11g);
    (p11g) = pos_c == 1 ? (p22g) : (p11g);
    (p22g) = pos_a == 2 ? tmp_a : (p22g);
    (p22g) = pos_b == 2 ? tmp_b : (p22g);
  };

  res |= p11g << 8;

  unsigned p00b, p01b, p02b;
  unsigned p10b, p11b, p12b;
  unsigned p20b, p21b, p22b;

  p00b = (p00 >> 16) & 255;
  p01b = (p01 >> 16) & 255;
  p02b = (p02 >> 16) & 255;
  p10b = (p10 >> 16) & 255;
  p11b = (p11 >> 16) & 255;
  p12b = (p12 >> 16) & 255;
  p20b = (p20 >> 16) & 255;
  p21b = (p21 >> 16) & 255;
  p22b = (p22 >> 16) & 255;

  {
    unsigned pos_a, pos_b, pos_c;
    unsigned tmp_a, tmp_b;
    unsigned a_bigger_b, a_bigger_c;
    unsigned b_bigger_c;
    a_bigger_b = (p00b) > (p01b);
    a_bigger_c = (p00b) > (p02b);
    b_bigger_c = (p01b) > (p02b);
    pos_a = a_bigger_c + a_bigger_b;
    pos_b = !a_bigger_b + b_bigger_c;
    pos_c = !a_bigger_c + !b_bigger_c;
    tmp_a = (p00b);
    tmp_b = (p01b);
    (p00b) = pos_b == 0 ? (p01b) : (p00b);
    (p00b) = pos_c == 0 ? (p02b) : (p00b);
    (p01b) = pos_a == 1 ? tmp_a : (p01b);
    (p01b) = pos_c == 1 ? (p02b) : (p01b);
    (p02b) = pos_a == 2 ? tmp_a : (p02b);
    (p02b) = pos_b == 2 ? tmp_b : (p02b);
  };
  {
    unsigned pos_a, pos_b, pos_c;
    unsigned tmp_a, tmp_b;
    unsigned a_bigger_b, a_bigger_c;
    unsigned b_bigger_c;
    a_bigger_b = (p10b) > (p11b);
    a_bigger_c = (p10b) > (p12b);
    b_bigger_c = (p11b) > (p12b);
    pos_a = a_bigger_c + a_bigger_b;
    pos_b = !a_bigger_b + b_bigger_c;
    pos_c = !a_bigger_c + !b_bigger_c;
    tmp_a = (p10b);
    tmp_b = (p11b);
    (p10b) = pos_b == 0 ? (p11b) : (p10b);
    (p10b) = pos_c == 0 ? (p12b) : (p10b);
    (p11b) = pos_a == 1 ? tmp_a : (p11b);
    (p11b) = pos_c == 1 ? (p12b) : (p11b);
    (p12b) = pos_a == 2 ? tmp_a : (p12b);
    (p12b) = pos_b == 2 ? tmp_b : (p12b);
  };
  {
    unsigned pos_a, pos_b, pos_c;
    unsigned tmp_a, tmp_b;
    unsigned a_bigger_b, a_bigger_c;
    unsigned b_bigger_c;
    a_bigger_b = (p20b) > (p21b);
    a_bigger_c = (p20b) > (p22b);
    b_bigger_c = (p21b) > (p22b);
    pos_a = a_bigger_c + a_bigger_b;
    pos_b = !a_bigger_b + b_bigger_c;
    pos_c = !a_bigger_c + !b_bigger_c;
    tmp_a = (p20b);
    tmp_b = (p21b);
    (p20b) = pos_b == 0 ? (p21b) : (p20b);
    (p20b) = pos_c == 0 ? (p22b) : (p20b);
    (p21b) = pos_a == 1 ? tmp_a : (p21b);
    (p21b) = pos_c == 1 ? (p22b) : (p21b);
    (p22b) = pos_a == 2 ? tmp_a : (p22b);
    (p22b) = pos_b == 2 ? tmp_b : (p22b);
  };

  {
    unsigned pos_a, pos_b, pos_c;
    unsigned tmp_a, tmp_b;
    unsigned a_bigger_b, a_bigger_c;
    unsigned b_bigger_c;
    a_bigger_b = (p00b) > (p10b);
    a_bigger_c = (p00b) > (p20b);
    b_bigger_c = (p10b) > (p20b);
    pos_a = a_bigger_c + a_bigger_b;
    pos_b = !a_bigger_b + b_bigger_c;
    pos_c = !a_bigger_c + !b_bigger_c;
    tmp_a = (p00b);
    tmp_b = (p10b);
    (p00b) = pos_b == 0 ? (p10b) : (p00b);
    (p00b) = pos_c == 0 ? (p20b) : (p00b);
    (p10b) = pos_a == 1 ? tmp_a : (p10b);
    (p10b) = pos_c == 1 ? (p20b) : (p10b);
    (p20b) = pos_a == 2 ? tmp_a : (p20b);
    (p20b) = pos_b == 2 ? tmp_b : (p20b);
  };
  {
    unsigned pos_a, pos_b, pos_c;
    unsigned tmp_a, tmp_b;
    unsigned a_bigger_b, a_bigger_c;
    unsigned b_bigger_c;
    a_bigger_b = (p01b) > (p11b);
    a_bigger_c = (p01b) > (p21b);
    b_bigger_c = (p11b) > (p21b);
    pos_a = a_bigger_c + a_bigger_b;
    pos_b = !a_bigger_b + b_bigger_c;
    pos_c = !a_bigger_c + !b_bigger_c;
    tmp_a = (p01b);
    tmp_b = (p11b);
    (p01b) = pos_b == 0 ? (p11b) : (p01b);
    (p01b) = pos_c == 0 ? (p21b) : (p01b);
    (p11b) = pos_a == 1 ? tmp_a : (p11b);
    (p11b) = pos_c == 1 ? (p21b) : (p11b);
    (p21b) = pos_a == 2 ? tmp_a : (p21b);
    (p21b) = pos_b == 2 ? tmp_b : (p21b);
  };
  {
    unsigned pos_a, pos_b, pos_c;
    unsigned tmp_a, tmp_b;
    unsigned a_bigger_b, a_bigger_c;
    unsigned b_bigger_c;
    a_bigger_b = (p02b) > (p12b);
    a_bigger_c = (p02b) > (p22b);
    b_bigger_c = (p12b) > (p22b);
    pos_a = a_bigger_c + a_bigger_b;
    pos_b = !a_bigger_b + b_bigger_c;
    pos_c = !a_bigger_c + !b_bigger_c;
    tmp_a = (p02b);
    tmp_b = (p12b);
    (p02b) = pos_b == 0 ? (p12b) : (p02b);
    (p02b) = pos_c == 0 ? (p22b) : (p02b);
    (p12b) = pos_a == 1 ? tmp_a : (p12b);
    (p12b) = pos_c == 1 ? (p22b) : (p12b);
    (p22b) = pos_a == 2 ? tmp_a : (p22b);
    (p22b) = pos_b == 2 ? tmp_b : (p22b);
  };

  {
    unsigned pos_a, pos_b, pos_c;
    unsigned tmp_a, tmp_b;
    unsigned a_bigger_b, a_bigger_c;
    unsigned b_bigger_c;
    a_bigger_b = (p00b) > (p11b);
    a_bigger_c = (p00b) > (p22b);
    b_bigger_c = (p11b) > (p22b);
    pos_a = a_bigger_c + a_bigger_b;
    pos_b = !a_bigger_b + b_bigger_c;
    pos_c = !a_bigger_c + !b_bigger_c;
    tmp_a = (p00b);
    tmp_b = (p11b);
    (p00b) = pos_b == 0 ? (p11b) : (p00b);
    (p00b) = pos_c == 0 ? (p22b) : (p00b);
    (p11b) = pos_a == 1 ? tmp_a : (p11b);
    (p11b) = pos_c == 1 ? (p22b) : (p11b);
    (p22b) = pos_a == 2 ? tmp_a : (p22b);
    (p22b) = pos_b == 2 ? tmp_b : (p22b);
  };

  res |= p11b << 16;

  out[hook(1, x * rowLen + y)] = res;
}