//{"_A":1,"ptr":0}
int hook(int argId, int id) {
	int gID = get_global_id(0);
	printf("%d,%d,%d\n", gID, argId, id);
	return id;
}
kernel void compute_sp_v4(global float* ptr, float _A) {
  float4 x = (float4)(_A, (_A + 1), (_A + 2), (_A + 3));
  float4 y = (float4)get_local_id(0);

  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  ;

  ptr[hook(0, get_global_id(0))] = (y.S0) + (y.S1) + (y.S2) + (y.S3);
}