//{"_A":1,"ptr":0}
int hook(int argId, int id) {
	int gID = get_global_id(0);
	printf("%d,%d,%d\n", gID, argId, id);
	return id;
}
kernel void compute_integer_v16(global int* ptr, int _A) {
  int16 x = (int16)(_A, (_A + 1), (_A + 2), (_A + 3), (_A + 4), (_A + 5), (_A + 6), (_A + 7), (_A + 8), (_A + 9), (_A + 10), (_A + 11), (_A + 12), (_A + 13), (_A + 14), (_A + 15));
  int16 y = (int16)get_local_id(0);

  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  ;

  int2 t = (y.S01) + (y.S23) + (y.S45) + (y.S67) + (y.S89) + (y.SAB) + (y.SCD) + (y.SEF);
  ptr[hook(0, get_global_id(0))] = t.S0 + t.S1;
}