//{"_A":1,"ptr":0}
int hook(int argId, int id) {
	int gID = get_global_id(0);
	printf("%d,%d,%d\n", gID, argId, id);
	return id;
}
kernel void compute_sp_v8(global float* ptr, float _A) {
  float8 x = (float8)(_A, (_A + 1), (_A + 2), (_A + 3), (_A + 4), (_A + 5), (_A + 6), (_A + 7));
  float8 y = (float8)get_local_id(0);

  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  ;

  ptr[hook(0, get_global_id(0))] = (y.S0) + (y.S1) + (y.S2) + (y.S3) + (y.S4) + (y.S5) + (y.S6) + (y.S7);
}