python3 test_preprocess.py --dataset="shoc" --src_folder="gpu-benchmarks/shoc/src/opencl"
python3 test_preprocess.py --dataset="amd" --src_folder="gpu-benchmarks/amd_sdk/cl"
python3 test_preprocess.py --dataset="rodinia" --src_folder="gpu-benchmarks/rodinia/opencl"
python3 test_preprocess.py --dataset="parboil" --src_folder="gpu-benchmarks/parboil/benchmarks"
python3 test_preprocess.py --dataset="nvidia" --src_folder="gpu-benchmarks/nvidia-sdk/" 