python3 test_preprocess.py --dataset="modified_amd" --src_folder="gpu-benchmarks-modified/amd/"
# python3 test_preprocess.py --dataset="modified_shoc" --src_folder="gpu-benchmarks-modified/shoc/"
# python3 test_preprocess.py --dataset="amd" --src_folder="gpu-benchmarks/amd_sdk/cl"
# python3 test_preprocess.py --dataset="rodinia" --src_folder="gpu-benchmarks/rodinia/opencl"
# python3 test_preprocess.py --dataset="parboil" --src_folder="gpu-benchmarks/parboil/benchmarks"
# python3 test_preprocess.py --dataset="nvidia" --src_folder="gpu-benchmarks/nvidia-sdk/" 