//{"_A":1,"ptr":0}
int hook(int argId, int id) {
	int gID = get_global_id(0);
	printf("%d,%d,%d\n", gID, argId, id);
	return id;
}
kernel void compute_integer_v4(global int* ptr, int _A) {
  int4 x = (int4)(_A, (_A + 1), (_A + 2), (_A + 3));
  int4 y = (int4)get_local_id(0);

  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  x = (y * x) + y;
  y = (x * y) + x;
  x = (y * x) + y;
  y = (x * y) + x;
  ;
  ;
  ;

  ptr[hook(0, get_global_id(0))] = (y.S0) + (y.S1) + (y.S2) + (y.S3);
}