//{"_A":1,"ptr":0}
int hook(int argId, int id) {
	int gID = get_global_id(0);
	printf("%d,%d,%d\n", gID, argId, id);
	return id;
}
kernel void compute_sp_v16(global float* ptr, float _A) {
  float16 x = (float16)(_A, (_A + 1), (_A + 2), (_A + 3), (_A + 4), (_A + 5), (_A + 6), (_A + 7), (_A + 8), (_A + 9), (_A + 10), (_A + 11), (_A + 12), (_A + 13), (_A + 14), (_A + 15));
  float16 y = (float16)get_local_id(0);

  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  x = mad(y, x, y);
  y = mad(x, y, x);
  x = mad(y, x, y);
  y = mad(x, y, x);
  ;
  ;
  ;

  float2 t = (y.S01) + (y.S23) + (y.S45) + (y.S67) + (y.S89) + (y.SAB) + (y.SCD) + (y.SEF);
  ptr[hook(0, get_global_id(0))] = t.S0 + t.S1;
}