//{"((__private uchar *)(key))":5,"((__private uchar *)(state))":6,"block":8,"hash":9,"nthash":0,"output":7,"rc4_iv":4,"result":2,"salts":1,"state":3}
int hook(int argId, int id) {
	int gID = get_global_id(0);
	printf("%d,%d,%d\n", gID, argId, id);
	return id;
}
typedef unsigned int UTF32;
typedef ushort UTF16;
typedef uchar UTF8;
constant unsigned int halfShift = 10;
constant UTF32 halfBase = 0x0010000U;
constant UTF32 halfMask = 0x3FFU;
constant char opt_trailingBytesUTF8[64] = {

    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5};

constant UTF32 offsetsFromUTF8[6] = {0x00000000UL, 0x00003080UL, 0x000E2080UL, 0x03C82080UL, 0xFA082080UL, 0x82082080UL};
inline unsigned int SWAP32(unsigned int x) {
  return bitselect(rotate(x, 24U), rotate(x, 8U), 0x00FF00FFU);
}
constant unsigned int rc4_iv[64] = {0x03020100, 0x07060504, 0x0b0a0908, 0x0f0e0d0c, 0x13121110, 0x17161514, 0x1b1a1918, 0x1f1e1d1c, 0x23222120, 0x27262524, 0x2b2a2928, 0x2f2e2d2c, 0x33323130, 0x37363534, 0x3b3a3938, 0x3f3e3d3c, 0x43424140, 0x47464544, 0x4b4a4948, 0x4f4e4d4c, 0x53525150, 0x57565554, 0x5b5a5958, 0x5f5e5d5c, 0x63626160, 0x67666564, 0x6b6a6968, 0x6f6e6d6c, 0x73727170, 0x77767574, 0x7b7a7978, 0x7f7e7d7c, 0x83828180, 0x87868584, 0x8b8a8988, 0x8f8e8d8c, 0x93929190, 0x97969594, 0x9b9a9998, 0x9f9e9d9c, 0xa3a2a1a0, 0xa7a6a5a4, 0xabaaa9a8, 0xafaeadac, 0xb3b2b1b0, 0xb7b6b5b4, 0xbbbab9b8, 0xbfbebdbc, 0xc3c2c1c0, 0xc7c6c5c4, 0xcbcac9c8, 0xcfcecdcc, 0xd3d2d1d0, 0xd7d6d5d4, 0xdbdad9d8, 0xdfdedddc, 0xe3e2e1e0, 0xe7e6e5e4, 0xebeae9e8, 0xefeeedec, 0xf3f2f1f0, 0xf7f6f5f4, 0xfbfaf9f8, 0xfffefdfc};
inline void rc4(

    const unsigned int* key,

    constant unsigned int* in, global unsigned int* out

) {
  unsigned int x;
  unsigned int y = 0;
  unsigned int index1 = 0;
  unsigned int index2 = 0;

  unsigned int state[256 / 4];

  for (x = 0; x < 256 / 4; x++)
    state[hook(3, x)] = rc4_iv[hook(4, x)];
  for (x = 0; x < 256; x++) {
    {
      {
        index2 = ((((uchar*)(key))[hook(5, (index1))]) + (((uchar*)(state))[hook(6, (x))]) + index2) & 255;
        {
          unsigned int tmp = (((uchar*)(state))[hook(6, (x))]);
          ((uchar*)(state))[hook(6, x)] = ((((uchar*)(state))[hook(6, (index2))]));
          ((uchar*)(state))[hook(6, index2)] = (tmp);
        };
      };
      index1++;
      x++;
    };
    {
      {
        index2 = ((((uchar*)(key))[hook(5, (index1))]) + (((uchar*)(state))[hook(6, (x))]) + index2) & 255;
        {
          unsigned int tmp = (((uchar*)(state))[hook(6, (x))]);
          ((uchar*)(state))[hook(6, x)] = ((((uchar*)(state))[hook(6, (index2))]));
          ((uchar*)(state))[hook(6, index2)] = (tmp);
        };
      };
      index1++;
      x++;
    };
    {
      {
        index2 = ((((uchar*)(key))[hook(5, (index1))]) + (((uchar*)(state))[hook(6, (x))]) + index2) & 255;
        {
          unsigned int tmp = (((uchar*)(state))[hook(6, (x))]);
          ((uchar*)(state))[hook(6, x)] = ((((uchar*)(state))[hook(6, (index2))]));
          ((uchar*)(state))[hook(6, index2)] = (tmp);
        };
      };
      index1++;
      x++;
    };
    {
      {
        index2 = ((((uchar*)(key))[hook(5, (index1))]) + (((uchar*)(state))[hook(6, (x))]) + index2) & 255;
        {
          unsigned int tmp = (((uchar*)(state))[hook(6, (x))]);
          ((uchar*)(state))[hook(6, x)] = ((((uchar*)(state))[hook(6, (index2))]));
          ((uchar*)(state))[hook(6, index2)] = (tmp);
        };
      };
      index1++;
      x++;
    };
    {
      {
        index2 = ((((uchar*)(key))[hook(5, (index1))]) + (((uchar*)(state))[hook(6, (x))]) + index2) & 255;
        {
          unsigned int tmp = (((uchar*)(state))[hook(6, (x))]);
          ((uchar*)(state))[hook(6, x)] = ((((uchar*)(state))[hook(6, (index2))]));
          ((uchar*)(state))[hook(6, index2)] = (tmp);
        };
      };
      index1++;
      x++;
    };
    {
      {
        index2 = ((((uchar*)(key))[hook(5, (index1))]) + (((uchar*)(state))[hook(6, (x))]) + index2) & 255;
        {
          unsigned int tmp = (((uchar*)(state))[hook(6, (x))]);
          ((uchar*)(state))[hook(6, x)] = ((((uchar*)(state))[hook(6, (index2))]));
          ((uchar*)(state))[hook(6, index2)] = (tmp);
        };
      };
      index1++;
      x++;
    };
    {
      {
        index2 = ((((uchar*)(key))[hook(5, (index1))]) + (((uchar*)(state))[hook(6, (x))]) + index2) & 255;
        {
          unsigned int tmp = (((uchar*)(state))[hook(6, (x))]);
          ((uchar*)(state))[hook(6, x)] = ((((uchar*)(state))[hook(6, (index2))]));
          ((uchar*)(state))[hook(6, index2)] = (tmp);
        };
      };
      index1++;
      x++;
    };
    {
      {
        index2 = ((((uchar*)(key))[hook(5, (index1))]) + (((uchar*)(state))[hook(6, (x))]) + index2) & 255;
        {
          unsigned int tmp = (((uchar*)(state))[hook(6, (x))]);
          ((uchar*)(state))[hook(6, x)] = ((((uchar*)(state))[hook(6, (index2))]));
          ((uchar*)(state))[hook(6, index2)] = (tmp);
        };
      };
      index1++;
      x++;
    };
    {
      {
        index2 = ((((uchar*)(key))[hook(5, (index1))]) + (((uchar*)(state))[hook(6, (x))]) + index2) & 255;
        {
          unsigned int tmp = (((uchar*)(state))[hook(6, (x))]);
          ((uchar*)(state))[hook(6, x)] = ((((uchar*)(state))[hook(6, (index2))]));
          ((uchar*)(state))[hook(6, index2)] = (tmp);
        };
      };
      index1++;
      x++;
    };
    {
      {
        index2 = ((((uchar*)(key))[hook(5, (index1))]) + (((uchar*)(state))[hook(6, (x))]) + index2) & 255;
        {
          unsigned int tmp = (((uchar*)(state))[hook(6, (x))]);
          ((uchar*)(state))[hook(6, x)] = ((((uchar*)(state))[hook(6, (index2))]));
          ((uchar*)(state))[hook(6, index2)] = (tmp);
        };
      };
      index1++;
      x++;
    };
    {
      {
        index2 = ((((uchar*)(key))[hook(5, (index1))]) + (((uchar*)(state))[hook(6, (x))]) + index2) & 255;
        {
          unsigned int tmp = (((uchar*)(state))[hook(6, (x))]);
          ((uchar*)(state))[hook(6, x)] = ((((uchar*)(state))[hook(6, (index2))]));
          ((uchar*)(state))[hook(6, index2)] = (tmp);
        };
      };
      index1++;
      x++;
    };
    {
      {
        index2 = ((((uchar*)(key))[hook(5, (index1))]) + (((uchar*)(state))[hook(6, (x))]) + index2) & 255;
        {
          unsigned int tmp = (((uchar*)(state))[hook(6, (x))]);
          ((uchar*)(state))[hook(6, x)] = ((((uchar*)(state))[hook(6, (index2))]));
          ((uchar*)(state))[hook(6, index2)] = (tmp);
        };
      };
      index1++;
      x++;
    };
    {
      {
        index2 = ((((uchar*)(key))[hook(5, (index1))]) + (((uchar*)(state))[hook(6, (x))]) + index2) & 255;
        {
          unsigned int tmp = (((uchar*)(state))[hook(6, (x))]);
          ((uchar*)(state))[hook(6, x)] = ((((uchar*)(state))[hook(6, (index2))]));
          ((uchar*)(state))[hook(6, index2)] = (tmp);
        };
      };
      index1++;
      x++;
    };
    {
      {
        index2 = ((((uchar*)(key))[hook(5, (index1))]) + (((uchar*)(state))[hook(6, (x))]) + index2) & 255;
        {
          unsigned int tmp = (((uchar*)(state))[hook(6, (x))]);
          ((uchar*)(state))[hook(6, x)] = ((((uchar*)(state))[hook(6, (index2))]));
          ((uchar*)(state))[hook(6, index2)] = (tmp);
        };
      };
      index1++;
      x++;
    };
    {
      {
        index2 = ((((uchar*)(key))[hook(5, (index1))]) + (((uchar*)(state))[hook(6, (x))]) + index2) & 255;
        {
          unsigned int tmp = (((uchar*)(state))[hook(6, (x))]);
          ((uchar*)(state))[hook(6, x)] = ((((uchar*)(state))[hook(6, (index2))]));
          ((uchar*)(state))[hook(6, index2)] = (tmp);
        };
      };
      index1++;
      x++;
    };
    {
      index2 = ((((uchar*)(key))[hook(5, (index1))]) + (((uchar*)(state))[hook(6, (x))]) + index2) & 255;
      {
        unsigned int tmp = (((uchar*)(state))[hook(6, (x))]);
        ((uchar*)(state))[hook(6, x)] = ((((uchar*)(state))[hook(6, (index2))]));
        ((uchar*)(state))[hook(6, index2)] = (tmp);
      };
    };
    index1 = 0;
  }
  for (x = 1; x <= 16; x++) {
    unsigned int xor_word;

    y = ((((uchar*)(state))[hook(6, (x))]) + y) & 255;
    {
      unsigned int tmp = (((uchar*)(state))[hook(6, (x))]);
      ((uchar*)(state))[hook(6, x)] = ((((uchar*)(state))[hook(6, (y))]));
      ((uchar*)(state))[hook(6, y)] = (tmp);
    };
    xor_word = (((uchar*)(state))[hook(6, (((((__private uchar *)(state))[(x)]) + (((_hook(6, (x))ivate uchar *)(state))[(hook(6, (y)))) & 255))]);
    x++;

    y = ((((uchar*)(state))[hook(6, (x))]) + y) & 255;
    {
      unsigned int tmp = (((uchar*)(state))[hook(6, (x))]);
      ((uchar*)(state))[hook(6, x)] = ((((uchar*)(state))[hook(6, (y))]));
      ((uchar*)(state))[hook(6, y)] = (tmp);
    };
    xor_word += (((uchar*)(state))[hook(6, (((((__private uchar *)(state))[(x)]) + (((_hook(6, (x))ivate uchar *)(state))[(hook(6, (y)))) & 255))]) << 8;
    x++;

    y = ((((uchar*)(state))[hook(6, (x))]) + y) & 255;
    {
      unsigned int tmp = (((uchar*)(state))[hook(6, (x))]);
      ((uchar*)(state))[hook(6, x)] = ((((uchar*)(state))[hook(6, (y))]));
      ((uchar*)(state))[hook(6, y)] = (tmp);
    };
    xor_word += (((uchar*)(state))[hook(6, (((((__private uchar *)(state))[(x)]) + (((_hook(6, (x))ivate uchar *)(state))[(hook(6, (y)))) & 255))]) << 16;
    x++;

    y = ((((uchar*)(state))[hook(6, (x))]) + y) & 255;
    {
      unsigned int tmp = (((uchar*)(state))[hook(6, (x))]);
      ((uchar*)(state))[hook(6, x)] = ((((uchar*)(state))[hook(6, (y))]));
      ((uchar*)(state))[hook(6, y)] = (tmp);
    };
    xor_word += (((uchar*)(state))[hook(6, (((((__private uchar *)(state))[(x)]) + (((_hook(6, (x))ivate uchar *)(state))[(hook(6, (y)))) & 255))]) << 24;

    *out++ = *in++ ^ xor_word;
  }
}
kernel void krb5pa_md5_final(const global unsigned int* nthash, constant unsigned int* salts, global unsigned int* result) {
  unsigned int i;
  unsigned int gid = get_global_id(0);
  unsigned int block[16];
  unsigned int output[4], hash[4];
  unsigned int a, b, c, d;

  {
    output[hook(7, 0)] = 0x67452301;
    output[hook(7, 1)] = 0xefcdab89;
    output[hook(7, 2)] = 0x98badcfe;
    output[hook(7, 3)] = 0x10325476;
  };

  for (i = 0; i < 4; i++)
    block[hook(8, i)] = 0x36363636 ^ nthash[hook(0, gid * 4 + i)];
  for (i = 4; i < 16; i++)
    block[hook(8, i)] = 0x36363636;
  {
    a = output[hook(7, 0)];
    b = output[hook(7, 1)];
    c = output[hook(7, 2)];
    d = output[hook(7, 3)];
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 0)]) + (0xd76aa478);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 1)]) + (0xe8c7b756);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 2)]) + (0x242070db);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 3)]) + (0xc1bdceee);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 4)]) + (0xf57c0faf);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 5)]) + (0x4787c62a);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 6)]) + (0xa8304613);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 7)]) + (0xfd469501);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 8)]) + (0x698098d8);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 9)]) + (0x8b44f7af);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 10)]) + (0xffff5bb1);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 11)]) + (0x895cd7be);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 12)]) + (0x6b901122);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 13)]) + (0xfd987193);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 14)]) + (0xa679438e);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 15)]) + (0x49b40821);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 1)]) + (0xf61e2562);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 6)]) + (0xc040b340);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 11)]) + (0x265e5a51);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 0)]) + (0xe9b6c7aa);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 5)]) + (0xd62f105d);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 10)]) + (0x02441453);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 15)]) + (0xd8a1e681);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 4)]) + (0xe7d3fbc8);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 9)]) + (0x21e1cde6);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 14)]) + (0xc33707d6);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 3)]) + (0xf4d50d87);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 8)]) + (0x455a14ed);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 13)]) + (0xa9e3e905);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 2)]) + (0xfcefa3f8);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 7)]) + (0x676f02d9);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 12)]) + (0x8d2a4c8a);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 5)]) + (0xfffa3942);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 8)]) + (0x8771f681);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 11)]) + (0x6d9d6122);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 14)]) + (0xfde5380c);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 1)]) + (0xa4beea44);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 4)]) + (0x4bdecfa9);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 7)]) + (0xf6bb4b60);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 10)]) + (0xbebfbc70);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 13)]) + (0x289b7ec6);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 0)]) + (0xeaa127fa);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 3)]) + (0xd4ef3085);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 6)]) + (0x04881d05);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 9)]) + (0xd9d4d039);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 12)]) + (0xe6db99e5);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 15)]) + (0x1fa27cf8);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 2)]) + (0xc4ac5665);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 0)]) + (0xf4292244);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 7)]) + (0x432aff97);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 14)]) + (0xab9423a7);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 5)]) + (0xfc93a039);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 12)]) + (0x655b59c3);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 3)]) + (0x8f0ccc92);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 10)]) + (0xffeff47d);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 1)]) + (0x85845dd1);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 8)]) + (0x6fa87e4f);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 15)]) + (0xfe2ce6e0);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 6)]) + (0xa3014314);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 13)]) + (0x4e0811a1);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 4)]) + (0xf7537e82);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 11)]) + (0xbd3af235);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 2)]) + (0x2ad7d2bb);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 9)]) + (0xeb86d391);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    output[hook(7, 0)] += a;
    output[hook(7, 1)] += b;
    output[hook(7, 2)] += c;
    output[hook(7, 3)] += d;
  };

  block[hook(8, 0)] = 0x01;
  block[hook(8, 1)] = 0x80;
  for (i = 2; i < 14; i++)
    block[hook(8, i)] = 0;
  block[hook(8, 14)] = (64 + 4) << 3;
  block[hook(8, 15)] = 0;
  {
    a = output[hook(7, 0)];
    b = output[hook(7, 1)];
    c = output[hook(7, 2)];
    d = output[hook(7, 3)];
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 0)]) + (0xd76aa478);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 1)]) + (0xe8c7b756);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 2)]) + (0x242070db);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 3)]) + (0xc1bdceee);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 4)]) + (0xf57c0faf);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 5)]) + (0x4787c62a);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 6)]) + (0xa8304613);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 7)]) + (0xfd469501);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 8)]) + (0x698098d8);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 9)]) + (0x8b44f7af);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 10)]) + (0xffff5bb1);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 11)]) + (0x895cd7be);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 12)]) + (0x6b901122);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 13)]) + (0xfd987193);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 14)]) + (0xa679438e);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 15)]) + (0x49b40821);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 1)]) + (0xf61e2562);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 6)]) + (0xc040b340);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 11)]) + (0x265e5a51);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 0)]) + (0xe9b6c7aa);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 5)]) + (0xd62f105d);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 10)]) + (0x02441453);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 15)]) + (0xd8a1e681);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 4)]) + (0xe7d3fbc8);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 9)]) + (0x21e1cde6);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 14)]) + (0xc33707d6);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 3)]) + (0xf4d50d87);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 8)]) + (0x455a14ed);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 13)]) + (0xa9e3e905);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 2)]) + (0xfcefa3f8);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 7)]) + (0x676f02d9);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 12)]) + (0x8d2a4c8a);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 5)]) + (0xfffa3942);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 8)]) + (0x8771f681);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 11)]) + (0x6d9d6122);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 14)]) + (0xfde5380c);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 1)]) + (0xa4beea44);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 4)]) + (0x4bdecfa9);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 7)]) + (0xf6bb4b60);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 10)]) + (0xbebfbc70);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 13)]) + (0x289b7ec6);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 0)]) + (0xeaa127fa);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 3)]) + (0xd4ef3085);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 6)]) + (0x04881d05);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 9)]) + (0xd9d4d039);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 12)]) + (0xe6db99e5);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 15)]) + (0x1fa27cf8);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 2)]) + (0xc4ac5665);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 0)]) + (0xf4292244);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 7)]) + (0x432aff97);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 14)]) + (0xab9423a7);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 5)]) + (0xfc93a039);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 12)]) + (0x655b59c3);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 3)]) + (0x8f0ccc92);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 10)]) + (0xffeff47d);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 1)]) + (0x85845dd1);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 8)]) + (0x6fa87e4f);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 15)]) + (0xfe2ce6e0);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 6)]) + (0xa3014314);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 13)]) + (0x4e0811a1);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 4)]) + (0xf7537e82);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 11)]) + (0xbd3af235);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 2)]) + (0x2ad7d2bb);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 9)]) + (0xeb86d391);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    output[hook(7, 0)] += a;
    output[hook(7, 1)] += b;
    output[hook(7, 2)] += c;
    output[hook(7, 3)] += d;
  };

  for (i = 0; i < 4; i++)
    hash[hook(9, i)] = output[hook(7, i)];
  for (i = 0; i < 4; i++)
    block[hook(8, i)] = 0x5c5c5c5c ^ nthash[hook(0, gid * 4 + i)];

  {
    output[hook(7, 0)] = 0x67452301;
    output[hook(7, 1)] = 0xefcdab89;
    output[hook(7, 2)] = 0x98badcfe;
    output[hook(7, 3)] = 0x10325476;
  };
  for (i = 4; i < 16; i++)
    block[hook(8, i)] = 0x5c5c5c5c;
  {
    a = output[hook(7, 0)];
    b = output[hook(7, 1)];
    c = output[hook(7, 2)];
    d = output[hook(7, 3)];
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 0)]) + (0xd76aa478);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 1)]) + (0xe8c7b756);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 2)]) + (0x242070db);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 3)]) + (0xc1bdceee);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 4)]) + (0xf57c0faf);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 5)]) + (0x4787c62a);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 6)]) + (0xa8304613);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 7)]) + (0xfd469501);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 8)]) + (0x698098d8);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 9)]) + (0x8b44f7af);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 10)]) + (0xffff5bb1);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 11)]) + (0x895cd7be);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 12)]) + (0x6b901122);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 13)]) + (0xfd987193);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 14)]) + (0xa679438e);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 15)]) + (0x49b40821);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 1)]) + (0xf61e2562);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 6)]) + (0xc040b340);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 11)]) + (0x265e5a51);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 0)]) + (0xe9b6c7aa);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 5)]) + (0xd62f105d);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 10)]) + (0x02441453);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 15)]) + (0xd8a1e681);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 4)]) + (0xe7d3fbc8);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 9)]) + (0x21e1cde6);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 14)]) + (0xc33707d6);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 3)]) + (0xf4d50d87);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 8)]) + (0x455a14ed);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 13)]) + (0xa9e3e905);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 2)]) + (0xfcefa3f8);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 7)]) + (0x676f02d9);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 12)]) + (0x8d2a4c8a);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 5)]) + (0xfffa3942);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 8)]) + (0x8771f681);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 11)]) + (0x6d9d6122);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 14)]) + (0xfde5380c);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 1)]) + (0xa4beea44);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 4)]) + (0x4bdecfa9);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 7)]) + (0xf6bb4b60);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 10)]) + (0xbebfbc70);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 13)]) + (0x289b7ec6);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 0)]) + (0xeaa127fa);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 3)]) + (0xd4ef3085);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 6)]) + (0x04881d05);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 9)]) + (0xd9d4d039);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 12)]) + (0xe6db99e5);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 15)]) + (0x1fa27cf8);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 2)]) + (0xc4ac5665);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 0)]) + (0xf4292244);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 7)]) + (0x432aff97);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 14)]) + (0xab9423a7);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 5)]) + (0xfc93a039);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 12)]) + (0x655b59c3);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 3)]) + (0x8f0ccc92);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 10)]) + (0xffeff47d);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 1)]) + (0x85845dd1);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 8)]) + (0x6fa87e4f);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 15)]) + (0xfe2ce6e0);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 6)]) + (0xa3014314);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 13)]) + (0x4e0811a1);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 4)]) + (0xf7537e82);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 11)]) + (0xbd3af235);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 2)]) + (0x2ad7d2bb);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 9)]) + (0xeb86d391);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    output[hook(7, 0)] += a;
    output[hook(7, 1)] += b;
    output[hook(7, 2)] += c;
    output[hook(7, 3)] += d;
  };

  for (i = 0; i < 4; i++)
    block[hook(8, i)] = hash[hook(9, i)];
  block[hook(8, 4)] = 0x80;
  for (i = 5; i < 14; i++)
    block[hook(8, i)] = 0;
  block[hook(8, 14)] = (64 + 16) << 3;
  block[hook(8, 15)] = 0;
  {
    a = output[hook(7, 0)];
    b = output[hook(7, 1)];
    c = output[hook(7, 2)];
    d = output[hook(7, 3)];
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 0)]) + (0xd76aa478);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 1)]) + (0xe8c7b756);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 2)]) + (0x242070db);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 3)]) + (0xc1bdceee);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 4)]) + (0xf57c0faf);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 5)]) + (0x4787c62a);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 6)]) + (0xa8304613);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 7)]) + (0xfd469501);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 8)]) + (0x698098d8);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 9)]) + (0x8b44f7af);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 10)]) + (0xffff5bb1);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 11)]) + (0x895cd7be);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 12)]) + (0x6b901122);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 13)]) + (0xfd987193);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 14)]) + (0xa679438e);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 15)]) + (0x49b40821);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 1)]) + (0xf61e2562);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 6)]) + (0xc040b340);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 11)]) + (0x265e5a51);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 0)]) + (0xe9b6c7aa);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 5)]) + (0xd62f105d);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 10)]) + (0x02441453);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 15)]) + (0xd8a1e681);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 4)]) + (0xe7d3fbc8);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 9)]) + (0x21e1cde6);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 14)]) + (0xc33707d6);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 3)]) + (0xf4d50d87);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 8)]) + (0x455a14ed);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 13)]) + (0xa9e3e905);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 2)]) + (0xfcefa3f8);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 7)]) + (0x676f02d9);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 12)]) + (0x8d2a4c8a);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 5)]) + (0xfffa3942);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 8)]) + (0x8771f681);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 11)]) + (0x6d9d6122);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 14)]) + (0xfde5380c);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 1)]) + (0xa4beea44);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 4)]) + (0x4bdecfa9);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 7)]) + (0xf6bb4b60);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 10)]) + (0xbebfbc70);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 13)]) + (0x289b7ec6);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 0)]) + (0xeaa127fa);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 3)]) + (0xd4ef3085);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 6)]) + (0x04881d05);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 9)]) + (0xd9d4d039);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 12)]) + (0xe6db99e5);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 15)]) + (0x1fa27cf8);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 2)]) + (0xc4ac5665);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 0)]) + (0xf4292244);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 7)]) + (0x432aff97);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 14)]) + (0xab9423a7);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 5)]) + (0xfc93a039);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 12)]) + (0x655b59c3);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 3)]) + (0x8f0ccc92);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 10)]) + (0xffeff47d);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 1)]) + (0x85845dd1);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 8)]) + (0x6fa87e4f);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 15)]) + (0xfe2ce6e0);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 6)]) + (0xa3014314);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 13)]) + (0x4e0811a1);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 4)]) + (0xf7537e82);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 11)]) + (0xbd3af235);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 2)]) + (0x2ad7d2bb);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 9)]) + (0xeb86d391);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    output[hook(7, 0)] += a;
    output[hook(7, 1)] += b;
    output[hook(7, 2)] += c;
    output[hook(7, 3)] += d;
  };

  for (i = 0; i < 4; i++)
    hash[hook(9, i)] = output[hook(7, i)];
  for (i = 0; i < 4; i++)
    block[hook(8, i)] = 0x36363636 ^ output[hook(7, i)];

  {
    output[hook(7, 0)] = 0x67452301;
    output[hook(7, 1)] = 0xefcdab89;
    output[hook(7, 2)] = 0x98badcfe;
    output[hook(7, 3)] = 0x10325476;
  };
  for (i = 4; i < 16; i++)
    block[hook(8, i)] = 0x36363636;
  {
    a = output[hook(7, 0)];
    b = output[hook(7, 1)];
    c = output[hook(7, 2)];
    d = output[hook(7, 3)];
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 0)]) + (0xd76aa478);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 1)]) + (0xe8c7b756);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 2)]) + (0x242070db);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 3)]) + (0xc1bdceee);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 4)]) + (0xf57c0faf);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 5)]) + (0x4787c62a);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 6)]) + (0xa8304613);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 7)]) + (0xfd469501);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 8)]) + (0x698098d8);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 9)]) + (0x8b44f7af);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 10)]) + (0xffff5bb1);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 11)]) + (0x895cd7be);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 12)]) + (0x6b901122);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 13)]) + (0xfd987193);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 14)]) + (0xa679438e);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 15)]) + (0x49b40821);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 1)]) + (0xf61e2562);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 6)]) + (0xc040b340);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 11)]) + (0x265e5a51);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 0)]) + (0xe9b6c7aa);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 5)]) + (0xd62f105d);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 10)]) + (0x02441453);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 15)]) + (0xd8a1e681);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 4)]) + (0xe7d3fbc8);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 9)]) + (0x21e1cde6);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 14)]) + (0xc33707d6);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 3)]) + (0xf4d50d87);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 8)]) + (0x455a14ed);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 13)]) + (0xa9e3e905);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 2)]) + (0xfcefa3f8);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 7)]) + (0x676f02d9);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 12)]) + (0x8d2a4c8a);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 5)]) + (0xfffa3942);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 8)]) + (0x8771f681);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 11)]) + (0x6d9d6122);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 14)]) + (0xfde5380c);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 1)]) + (0xa4beea44);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 4)]) + (0x4bdecfa9);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 7)]) + (0xf6bb4b60);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 10)]) + (0xbebfbc70);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 13)]) + (0x289b7ec6);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 0)]) + (0xeaa127fa);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 3)]) + (0xd4ef3085);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 6)]) + (0x04881d05);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 9)]) + (0xd9d4d039);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 12)]) + (0xe6db99e5);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 15)]) + (0x1fa27cf8);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 2)]) + (0xc4ac5665);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 0)]) + (0xf4292244);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 7)]) + (0x432aff97);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 14)]) + (0xab9423a7);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 5)]) + (0xfc93a039);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 12)]) + (0x655b59c3);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 3)]) + (0x8f0ccc92);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 10)]) + (0xffeff47d);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 1)]) + (0x85845dd1);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 8)]) + (0x6fa87e4f);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 15)]) + (0xfe2ce6e0);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 6)]) + (0xa3014314);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 13)]) + (0x4e0811a1);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 4)]) + (0xf7537e82);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 11)]) + (0xbd3af235);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 2)]) + (0x2ad7d2bb);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 9)]) + (0xeb86d391);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    output[hook(7, 0)] += a;
    output[hook(7, 1)] += b;
    output[hook(7, 2)] += c;
    output[hook(7, 3)] += d;
  };

  for (i = 0; i < 4; i++)
    block[hook(8, i)] = *salts++;
  block[hook(8, 4)] = 0x80;
  for (i = 5; i < 14; i++)
    block[hook(8, i)] = 0;
  block[hook(8, 14)] = (64 + 16) << 3;
  block[hook(8, 15)] = 0;
  {
    a = output[hook(7, 0)];
    b = output[hook(7, 1)];
    c = output[hook(7, 2)];
    d = output[hook(7, 3)];
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 0)]) + (0xd76aa478);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 1)]) + (0xe8c7b756);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 2)]) + (0x242070db);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 3)]) + (0xc1bdceee);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 4)]) + (0xf57c0faf);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 5)]) + (0x4787c62a);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 6)]) + (0xa8304613);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 7)]) + (0xfd469501);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 8)]) + (0x698098d8);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 9)]) + (0x8b44f7af);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 10)]) + (0xffff5bb1);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 11)]) + (0x895cd7be);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 12)]) + (0x6b901122);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 13)]) + (0xfd987193);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 14)]) + (0xa679438e);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 15)]) + (0x49b40821);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 1)]) + (0xf61e2562);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 6)]) + (0xc040b340);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 11)]) + (0x265e5a51);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 0)]) + (0xe9b6c7aa);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 5)]) + (0xd62f105d);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 10)]) + (0x02441453);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 15)]) + (0xd8a1e681);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 4)]) + (0xe7d3fbc8);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 9)]) + (0x21e1cde6);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 14)]) + (0xc33707d6);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 3)]) + (0xf4d50d87);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 8)]) + (0x455a14ed);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 13)]) + (0xa9e3e905);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 2)]) + (0xfcefa3f8);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 7)]) + (0x676f02d9);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 12)]) + (0x8d2a4c8a);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 5)]) + (0xfffa3942);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 8)]) + (0x8771f681);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 11)]) + (0x6d9d6122);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 14)]) + (0xfde5380c);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 1)]) + (0xa4beea44);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 4)]) + (0x4bdecfa9);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 7)]) + (0xf6bb4b60);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 10)]) + (0xbebfbc70);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 13)]) + (0x289b7ec6);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 0)]) + (0xeaa127fa);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 3)]) + (0xd4ef3085);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 6)]) + (0x04881d05);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 9)]) + (0xd9d4d039);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 12)]) + (0xe6db99e5);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 15)]) + (0x1fa27cf8);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 2)]) + (0xc4ac5665);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 0)]) + (0xf4292244);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 7)]) + (0x432aff97);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 14)]) + (0xab9423a7);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 5)]) + (0xfc93a039);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 12)]) + (0x655b59c3);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 3)]) + (0x8f0ccc92);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 10)]) + (0xffeff47d);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 1)]) + (0x85845dd1);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 8)]) + (0x6fa87e4f);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 15)]) + (0xfe2ce6e0);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 6)]) + (0xa3014314);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 13)]) + (0x4e0811a1);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 4)]) + (0xf7537e82);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 11)]) + (0xbd3af235);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 2)]) + (0x2ad7d2bb);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 9)]) + (0xeb86d391);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    output[hook(7, 0)] += a;
    output[hook(7, 1)] += b;
    output[hook(7, 2)] += c;
    output[hook(7, 3)] += d;
  };

  for (i = 0; i < 4; i++)
    block[hook(8, i)] = 0x5c5c5c5c ^ hash[hook(9, i)];
  for (i = 0; i < 4; i++)
    hash[hook(9, i)] = output[hook(7, i)];

  {
    output[hook(7, 0)] = 0x67452301;
    output[hook(7, 1)] = 0xefcdab89;
    output[hook(7, 2)] = 0x98badcfe;
    output[hook(7, 3)] = 0x10325476;
  };
  for (i = 4; i < 16; i++)
    block[hook(8, i)] = 0x5c5c5c5c;
  {
    a = output[hook(7, 0)];
    b = output[hook(7, 1)];
    c = output[hook(7, 2)];
    d = output[hook(7, 3)];
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 0)]) + (0xd76aa478);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 1)]) + (0xe8c7b756);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 2)]) + (0x242070db);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 3)]) + (0xc1bdceee);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 4)]) + (0xf57c0faf);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 5)]) + (0x4787c62a);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 6)]) + (0xa8304613);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 7)]) + (0xfd469501);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 8)]) + (0x698098d8);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 9)]) + (0x8b44f7af);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 10)]) + (0xffff5bb1);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 11)]) + (0x895cd7be);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 12)]) + (0x6b901122);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 13)]) + (0xfd987193);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 14)]) + (0xa679438e);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 15)]) + (0x49b40821);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 1)]) + (0xf61e2562);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 6)]) + (0xc040b340);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 11)]) + (0x265e5a51);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 0)]) + (0xe9b6c7aa);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 5)]) + (0xd62f105d);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 10)]) + (0x02441453);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 15)]) + (0xd8a1e681);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 4)]) + (0xe7d3fbc8);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 9)]) + (0x21e1cde6);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 14)]) + (0xc33707d6);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 3)]) + (0xf4d50d87);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 8)]) + (0x455a14ed);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 13)]) + (0xa9e3e905);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 2)]) + (0xfcefa3f8);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 7)]) + (0x676f02d9);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 12)]) + (0x8d2a4c8a);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 5)]) + (0xfffa3942);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 8)]) + (0x8771f681);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 11)]) + (0x6d9d6122);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 14)]) + (0xfde5380c);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 1)]) + (0xa4beea44);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 4)]) + (0x4bdecfa9);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 7)]) + (0xf6bb4b60);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 10)]) + (0xbebfbc70);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 13)]) + (0x289b7ec6);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 0)]) + (0xeaa127fa);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 3)]) + (0xd4ef3085);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 6)]) + (0x04881d05);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 9)]) + (0xd9d4d039);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 12)]) + (0xe6db99e5);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 15)]) + (0x1fa27cf8);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 2)]) + (0xc4ac5665);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 0)]) + (0xf4292244);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 7)]) + (0x432aff97);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 14)]) + (0xab9423a7);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 5)]) + (0xfc93a039);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 12)]) + (0x655b59c3);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 3)]) + (0x8f0ccc92);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 10)]) + (0xffeff47d);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 1)]) + (0x85845dd1);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 8)]) + (0x6fa87e4f);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 15)]) + (0xfe2ce6e0);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 6)]) + (0xa3014314);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 13)]) + (0x4e0811a1);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 4)]) + (0xf7537e82);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 11)]) + (0xbd3af235);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 2)]) + (0x2ad7d2bb);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 9)]) + (0xeb86d391);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    output[hook(7, 0)] += a;
    output[hook(7, 1)] += b;
    output[hook(7, 2)] += c;
    output[hook(7, 3)] += d;
  };

  for (i = 0; i < 4; i++)
    block[hook(8, i)] = hash[hook(9, i)];
  block[hook(8, 4)] = 0x80;
  for (i = 5; i < 14; i++)
    block[hook(8, i)] = 0;
  block[hook(8, 14)] = (64 + 16) << 3;
  block[hook(8, 15)] = 0;
  {
    a = output[hook(7, 0)];
    b = output[hook(7, 1)];
    c = output[hook(7, 2)];
    d = output[hook(7, 3)];
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 0)]) + (0xd76aa478);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 1)]) + (0xe8c7b756);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 2)]) + (0x242070db);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 3)]) + (0xc1bdceee);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 4)]) + (0xf57c0faf);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 5)]) + (0x4787c62a);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 6)]) + (0xa8304613);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 7)]) + (0xfd469501);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 8)]) + (0x698098d8);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 9)]) + (0x8b44f7af);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 10)]) + (0xffff5bb1);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 11)]) + (0x895cd7be);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((d)), ((c)), ((b))) + (block[hook(8, 12)]) + (0x6b901122);
    (a) = rotate((a), (unsigned int)(7));
    (a) += (b);
    (d) += bitselect(((c)), ((b)), ((a))) + (block[hook(8, 13)]) + (0xfd987193);
    (d) = rotate((d), (unsigned int)(12));
    (d) += (a);
    (c) += bitselect(((b)), ((a)), ((d))) + (block[hook(8, 14)]) + (0xa679438e);
    (c) = rotate((c), (unsigned int)(17));
    (c) += (d);
    (b) += bitselect(((a)), ((d)), ((c))) + (block[hook(8, 15)]) + (0x49b40821);
    (b) = rotate((b), (unsigned int)(22));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 1)]) + (0xf61e2562);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 6)]) + (0xc040b340);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 11)]) + (0x265e5a51);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 0)]) + (0xe9b6c7aa);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 5)]) + (0xd62f105d);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 10)]) + (0x02441453);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 15)]) + (0xd8a1e681);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 4)]) + (0xe7d3fbc8);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 9)]) + (0x21e1cde6);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 14)]) + (0xc33707d6);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 3)]) + (0xf4d50d87);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 8)]) + (0x455a14ed);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += bitselect(((c)), ((b)), ((d))) + (block[hook(8, 13)]) + (0xa9e3e905);
    (a) = rotate((a), (unsigned int)(5));
    (a) += (b);
    (d) += bitselect(((b)), ((a)), ((c))) + (block[hook(8, 2)]) + (0xfcefa3f8);
    (d) = rotate((d), (unsigned int)(9));
    (d) += (a);
    (c) += bitselect(((a)), ((d)), ((b))) + (block[hook(8, 7)]) + (0x676f02d9);
    (c) = rotate((c), (unsigned int)(14));
    (c) += (d);
    (b) += bitselect(((d)), ((c)), ((a))) + (block[hook(8, 12)]) + (0x8d2a4c8a);
    (b) = rotate((b), (unsigned int)(20));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 5)]) + (0xfffa3942);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 8)]) + (0x8771f681);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 11)]) + (0x6d9d6122);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 14)]) + (0xfde5380c);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 1)]) + (0xa4beea44);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 4)]) + (0x4bdecfa9);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 7)]) + (0xf6bb4b60);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 10)]) + (0xbebfbc70);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 13)]) + (0x289b7ec6);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 0)]) + (0xeaa127fa);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 3)]) + (0xd4ef3085);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 6)]) + (0x04881d05);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((b)) ^ ((c)) ^ ((d))) + (block[hook(8, 9)]) + (0xd9d4d039);
    (a) = rotate((a), (unsigned int)(4));
    (a) += (b);
    (d) += (((a)) ^ ((b)) ^ ((c))) + (block[hook(8, 12)]) + (0xe6db99e5);
    (d) = rotate((d), (unsigned int)(11));
    (d) += (a);
    (c) += (((d)) ^ ((a)) ^ ((b))) + (block[hook(8, 15)]) + (0x1fa27cf8);
    (c) = rotate((c), (unsigned int)(16));
    (c) += (d);
    (b) += (((c)) ^ ((d)) ^ ((a))) + (block[hook(8, 2)]) + (0xc4ac5665);
    (b) = rotate((b), (unsigned int)(23));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 0)]) + (0xf4292244);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 7)]) + (0x432aff97);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 14)]) + (0xab9423a7);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 5)]) + (0xfc93a039);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 12)]) + (0x655b59c3);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 3)]) + (0x8f0ccc92);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 10)]) + (0xffeff47d);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 1)]) + (0x85845dd1);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 8)]) + (0x6fa87e4f);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 15)]) + (0xfe2ce6e0);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 6)]) + (0xa3014314);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 13)]) + (0x4e0811a1);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    (a) += (((c)) ^ (((b)) | ~((d)))) + (block[hook(8, 4)]) + (0xf7537e82);
    (a) = rotate((a), (unsigned int)(6));
    (a) += (b);
    (d) += (((b)) ^ (((a)) | ~((c)))) + (block[hook(8, 11)]) + (0xbd3af235);
    (d) = rotate((d), (unsigned int)(10));
    (d) += (a);
    (c) += (((a)) ^ (((d)) | ~((b)))) + (block[hook(8, 2)]) + (0x2ad7d2bb);
    (c) = rotate((c), (unsigned int)(15));
    (c) += (d);
    (b) += (((d)) ^ (((c)) | ~((a)))) + (block[hook(8, 9)]) + (0xeb86d391);
    (b) = rotate((b), (unsigned int)(21));
    (b) += (c);
    output[hook(7, 0)] += a;
    output[hook(7, 1)] += b;
    output[hook(7, 2)] += c;
    output[hook(7, 3)] += d;
  };

  rc4(output, salts, &result[hook(2, gid * 4)]);
}